#配置工程访问地址
server:
  servlet:
    context-path: /dictionary
  port: 9999

spring:
  mvc:
    static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dictionary
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
